const whatsappLink = "https://wa.me/message/FYHMTR6WLLO3F1";
const pillars = [
  {n:'01', title:'Destrave', sub:'Diagnóstico estratégico + clareza comercial', text:'Você vai entender, de forma direta, o que está travando suas vendas e quais ajustes podem impulsioná-las.'},
  {n:'02', title:'Implementação', sub:'Captação + follow-up + primeira campanha de vendas', text:'Aqui você entra em movimento real. Aplicamos estratégias para gerar conversas, despertar interesse e vender com mais segurança e consistência — incluindo as primeiras campanhas e um sistema inteligente de CRM e follow-up.'},
  {n:'03', title:'Expansão', sub:'Vendas consistentes + posicionamento + campanhas mensais', text:'A estrutura evolui para sustentar vendas mais consistentes, presença de marca e campanhas mensais alinhadas ao momento do negócio.'},
];
const deliverables = ['Encontros individuais quinzenais com direção estratégica','Implementação de tráfego pago pelo Meta Ads e Google Ads','Criação de toda a estrutura inicial dos anúncios','3 meses de acompanhamento','Análise do posicionamento atual e da percepção de valor','Reposicionamento com foco em atração e conversão','Clareza de público-alvo, linguagem e diferencial competitivo','Construção de campanhas de vendas internas e externas','Implementação de uma rotina comercial que converte','Estratégias de encantamento e fidelização de clientes'];
export default function Mentoria(){return <main>
  <section className="hero mentor-hero"><header className="site-header shell"><a className="brand" href="/"><img className="brand-logo" src="/brand/digital-beauty.png" alt="Digital Beauty" /></a><nav className="main-nav"><a href="/">Início</a><a href="/gestao-de-anuncios">Gestão de Anúncios</a></nav></header>
  <div className="mentor-hero-content mentor-hero-content-simple shell"><div><span className="eyebrow eyebrow-light">MENTORIA INDIVIDUAL DE IMPLEMENTAÇÃO</span><h1>Mentoria Destravando Seu Negócio: da captação à <span className="text-highlight">conversão de pacientes.</span></h1><p className="mentor-hero-lead">Para profissionais de estética que querem sair da estagnação e criar um fluxo de atração, qualificação e conversão que trabalha por elas.</p></div></div></section>
  <section className="mentor-section section-light" id="pilares"><div className="shell"><div className="mentor-heading section-grid"><div className="section-label"><span>01</span><i /></div><div><span className="eyebrow">O CAMINHO DE IMPLEMENTAÇÃO</span><h2>Três pilares para tirar a estratégia do papel.</h2></div></div><div className="pillar-grid">{pillars.map(p=><article className="pillar-card" key={p.n}><span>{p.n}</span><h3>{p.title}</h3><strong>{p.sub}</strong><p>{p.text}</p></article>)}</div></div></section>
  <section className="mentor-section section-dark"><div className="shell"><div className="mentor-heading section-grid"><div className="section-label section-label-light"><span>02</span><i /></div><div><span className="eyebrow eyebrow-light">O QUE É ENTREGUE</span><h2>Direção individual e implementação <span className="text-highlight">lado a lado.</span></h2><p className="mentor-intro mentor-intro-light">A DSN não é um curso gravado. É um acompanhamento de três meses para construir e aplicar a estrutura comercial do seu negócio.</p></div></div><ul className="deliverables-grid">{deliverables.map((d,i)=><li key={d}><span>0{i+1}</span>{d}</li>)}</ul></div></section>
  <section className="mentor-logic mentor-section"><div className="shell logic-grid"><div className="section-label"><span>03</span><i /></div><div className="logic-content"><span className="eyebrow">PRÓXIMO PASSO</span><h2>Quer dar o próximo passo e fazer parte da DSN?</h2><p className="mentor-intro">No WhatsApp, você recebe os detalhes do acompanhamento e pode avaliar com clareza se essa é a estrutura certa para o seu negócio.</p><a className="mentor-cta" href={whatsappLink} target="_blank" rel="noreferrer">Quero saber como funciona a Mentoria DSN <span>↗</span></a></div></div></section>
  <footer className="site-footer"><div className="shell"><img src="/brand/digital-beauty.png" alt="Digital Beauty"/><nav><a href="/">Início</a><a href="/gestao-de-anuncios">Gestão</a><a href="/mentoria">Mentoria</a></nav><div className="footer-meta"><p>Todos os direitos reservados à Eloisa Aguiar | CNPJ 56.129.391/0001-01</p><div><a href="https://eloaguiar.br" target="_blank" rel="noreferrer">eloaguiar.br</a><a href="https://www.instagram.com/eloaguiar.br/" target="_blank" rel="noreferrer">@eloaguiar.br</a></div></div></div></footer>
  </main>}
